# Generated by Django 4.0.6 on 2022-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='color_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
